version: '3.8'

services:

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ai_user
      POSTGRES_PASSWORD: ai_pass
      POSTGRES_DB: ai_pipeline
    ports:
      - "5432:5432"
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -d ai_pipeline -U ai_user" ]
#      interval: 5s
#      timeout: 5s
#      retries: 10
#      start_period: 10s
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data


  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka_broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,EXTERNAL://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
#    healthcheck:
#      test: [ "CMD", "nc", "-z", "localhost", "9092" ]
#      interval: 10s
#      timeout: 5s
#      retries: 10
#      start_period: 30s
    volumes:
      - kafka_data:/var/lib/kafka/data


  app:
    build: .
    container_name: ai_app
    depends_on:
      - db
#        condition: service_healthy
      - kafka
#        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ai_pipeline
      SPRING_DATASOURCE_USERNAME: ai_user
      SPRING_DATASOURCE_PASSWORD: ai_pass
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    restart: always
volumes:
  postgres_data:
  kafka_data: