spring:
  kafka:
    bootstrap-servers: ${spring.embedded.kafka.brokers}
    consumer:
      auto-offset-reset: earliest
      group-id: test-group
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topics:
      incoming: ai.processing.raw
      outgoing: ai.candidate.filtered
      dlq: ai.processing.deserialization.dlq
      processing-dlq: ai.processing.business.dlq