spring:
  kafka:
    bootstrap-servers: ${spring.embedded.kafka.brokers}
#    producer:
#      transaction-id-prefix: test-tx-${random.uuid}-
    consumer:
      auto-offset-reset: earliest
      group-id: test-group
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
    topics:
      incoming: ai.processing.raw
      outgoing: ai.candidate.filtered
      processing-dlq: ai.processing.business.dlq
